name: sars_susceptibles

channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - entrez-direct=13.9
  - mafft=7.471
  - r-base=4.0.3
  - rstudio=1
  - r-dplyr=1.0.2
  - r-tidyr=1.1.2
  - r-readr=1.4.0
  - r-readxl=1.3.1
  - r-stringr=1.4.0
  - r-seqinr=4.2_4
  - r-caret=6.0_86
  - r-modelmetrics=1.2.2
  - r-xgboost=1.2.0