name: sars_susceptibles

channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - entrez-direct=13.9
  - mafft=7.471
  - r-base=4.0.3
  - rstudio=1
  - r-rprojroot=2.0.2
  - r-dplyr=1.0.2
  - r-tidyr=1.1.2
  - r-readr=1.4.0
  - r-stringr=1.4.0
  - r-seqinr=4.2_4
  - r-ggplot2=3.3.2
  - r-cowplot=1.1.0
  - r-plotroc=2.2.1
  - r-vegan=2.5_6
  - r-apcluster=1.4.8
  - r-caret=6.0_86
  - r-e1071=1.7_4
  - r-doParallel=1.0.16
  - r-modelmetrics=1.2.2
  - r-xgboost=1.2.0