name: sars_susceptibles

channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - entrez-direct=13.9
  - mafft=7.471
  - r-base=4.0.3  
  - r-argparse=2.0.3
  - r-dplyr=1.0.5
  - r-tidyr=1.1.3
  - r-readr=1.4.0
  - r-readxl=1.3.1
  - r-stringr=1.4.0
  - r-seqinr=4.2_4
  - r-ggplot2=3.3.3
  - r-cowplot=1.1.1
  - r-caret=6.0_86
  - r-e1071=1.7_4
  - r-doParallel=1.0.16
  - r-modelmetrics=1.2.2
  - r-xgboost=1.3.3