name: sars_susceptibles

channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - entrez-direct=13.9
  - mafft=7.471
  - iqtree=1.6.12
  - r-base=4.1.0
  - r-argparse=2.0.3
  - r-dplyr=1.0.7
  - r-tidyr=1.1.3
  - r-readr=1.4.0
  - r-readxl=1.3.1
  - r-stringr=1.4.0
  - r-seqinr=4.2_8
  - r-ape=5.5
  - r-dendextend=1.15.1
  - r-phylogram=2.1.0
  - r-ggplot2=3.3.5
  - bioconductor-ggtree=3.0.1
  - r-cowplot=1.1.1
  - r-tidymodels=0.1.3
  - r-themis=0.1.4
  - r-furrr=0.2.3
  - r-doFuture=0.12.0
  - r-xgboost=1.4.0
  - r-apcluster=1.4.8
  - r-sf=1.0_1
  - r-raster=3.4_13
  - r-taxize=0.9.99
  - r-phytools=0.7_80 
  - r-ggbeeswarm=0.6.0
  - r-ggsignif=0.6.2
  - r-unix=1.5
